# Generated by Django 3.2.7 on 2021-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='metup',
            name='participant',
            field=models.ManyToManyField(blank=True, to='meetups.Participant'),
        ),
    ]
