# Generated by Django 3.2.7 on 2021-09-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_metup_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='metup',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
